version: '3.8'
services:
  db:
    image: postgres:15
    container_name: test-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testtest
      POSTGRES_DB: testdb
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  test_db_data:
